<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TarkovAssistant.Data\TarkovAssistant.Data.csproj" />
    <ProjectReference Include="..\TarkovAssistant.Domain\TarkovAssistant.Domain.csproj" />
  </ItemGroup>

</Project>
