<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\map_coop_extract.png" />
    <None Remove="Resources\Images\map_pmc_extract.png" />
    <None Remove="Resources\Images\map_quest.png" />
    <None Remove="Resources\Images\map_quest_blue.png" />
    <None Remove="Resources\Images\map_quest_green.png" />
    <None Remove="Resources\Images\map_scav_extract.png" />
    <None Remove="Resources\Images\map_transit_extract.png" />
    <None Remove="Resources\Images\Traders\trader_fence.png" />
    <None Remove="Resources\Images\Traders\trader_jaeger.png" />
    <None Remove="Resources\Images\Traders\trader_lightkeeper.png" />
    <None Remove="Resources\Images\Traders\trader_mechanic.png" />
    <None Remove="Resources\Images\Traders\trader_peacemaker.png" />
    <None Remove="Resources\Images\Traders\trader_ragman.png" />
    <None Remove="Resources\Images\Traders\trader_skier.png" />
    <None Remove="Resources\Images\Traders\trader_therapist.png" />
    <None Remove="Resources\Images\Traders\trader_unknown.png" />
    <None Remove="Resources\Images\trader_prapor.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\app_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.141" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TarkovAssistant.Data\TarkovAssistant.Data.csproj" />
    <ProjectReference Include="..\TarkovAssistant.Domain\TarkovAssistant.Domain.csproj" />
    <ProjectReference Include="..\TarkovAssistant.Services\TarkovAssistant.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\map_coop_extract.png" />
    <Resource Include="Resources\Images\map_pmc_extract.png" />
    <Resource Include="Resources\Images\map_quest_blue.png" />
    <Resource Include="Resources\Images\map_quest_green.png" />
    <Resource Include="Resources\Images\map_scav_extract.png" />
    <Resource Include="Resources\Images\map_transit_extract.png" />
    <Resource Include="Resources\Images\Traders\trader_fence.png" />
    <Resource Include="Resources\Images\Traders\trader_jaeger.png" />
    <Resource Include="Resources\Images\Traders\trader_lightkeeper.png" />
    <Resource Include="Resources\Images\Traders\trader_mechanic.png" />
    <Resource Include="Resources\Images\Traders\trader_peacemaker.png" />
    <Resource Include="Resources\Images\Traders\trader_prapor.png" />
    <Resource Include="Resources\Images\Traders\trader_ragman.png" />
    <Resource Include="Resources\Images\Traders\trader_skier.png" />
    <Resource Include="Resources\Images\Traders\trader_therapist.png" />
    <Resource Include="Resources\Images\Traders\trader_unknown.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Labels.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Labels.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Labels.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Labels.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
